/**
 * Catálogo de ejercicios sueltos del Hub Recursos.
 *
 * Ejercicios extraídos de los cuadernos para hacerlos en 3-10 min sin
 * comprometerse al cuaderno entero. Cada uno apunta a su cuaderno padre.
 *
 * Inspirado en HTML "Diario Recurso" sección "Otros recursos".
 */

export type ExerciseCatalogEntry = {
  id: string;
  title: string;
  duration: string;
  type: 'ejercicio' | 'lectura' | 'pausa';
  kicker: string; // tag inicial pequeño
  fromCuaderno: { slug: string; title: string };
  pageIndex: number; // página del cuaderno
  icon: string;
  color: 'cobalto' | 'coral' | 'mostaza';
};

export const EXERCISES_CATALOG: ExerciseCatalogEntry[] = [
  {
    id: 'notar-sin-etiqueta',
    title: 'Notar sin etiqueta',
    duration: '5 min',
    type: 'ejercicio',
    kicker: 'Día 1 · de 5',
    fromCuaderno: { slug: 'hipervigilancia', title: 'Hipervigilancia' },
    pageIndex: 4,
    icon: '·',
    color: 'cobalto',
  },
  {
    id: 'cuerpo-primero',
    title: 'El cuerpo primero',
    duration: '5 min',
    type: 'ejercicio',
    kicker: 'Día 4 · de 5',
    fromCuaderno: { slug: 'hipervigilancia', title: 'Hipervigilancia' },
    pageIndex: 9,
    icon: '◯',
    color: 'mostaza',
  },
  {
    id: 'tu-ratio-personal',
    title: 'Tu ratio personal de pareja',
    duration: '7 días',
    type: 'ejercicio',
    kicker: 'Gottman 5:1',
    fromCuaderno: { slug: 'reparar-gottman', title: 'Reparar · Gottman' },
    pageIndex: 4,
    icon: '5:1',
    color: 'coral',
  },
  {
    id: 'tu-mapa-cuidado',
    title: 'Tu mapa de cuidado',
    duration: '~15 min',
    type: 'ejercicio',
    kicker: 'Lenguajes del amor',
    fromCuaderno: { slug: 'lenguajes-amor', title: 'Los lenguajes del amor' },
    pageIndex: 6,
    icon: '♡',
    color: 'coral',
  },
  {
    id: 'diez-emociones-semana',
    title: 'Las diez de la semana',
    duration: '~10 min',
    type: 'ejercicio',
    kicker: 'Día 1 · de 4',
    fromCuaderno: { slug: 'mapa-emociones', title: 'El mapa de tus emociones' },
    pageIndex: 4,
    icon: '10',
    color: 'mostaza',
  },
  {
    id: 'carta-tres-emociones',
    title: 'Carta a tres emociones',
    duration: '~15 min',
    type: 'ejercicio',
    kicker: 'Día 3 · de 4',
    fromCuaderno: { slug: 'mapa-emociones', title: 'El mapa de tus emociones' },
    pageIndex: 9,
    icon: '✉',
    color: 'cobalto',
  },
  {
    id: 'linea-de-vida',
    title: 'La línea de vida',
    duration: '~20 min',
    type: 'ejercicio',
    kicker: 'Fortalezas',
    fromCuaderno: { slug: 'fortalezas-linea-vida', title: 'Tus fortalezas' },
    pageIndex: 6,
    icon: '⌇',
    color: 'mostaza',
  },
  {
    id: 'pausa-narradora',
    title: 'No estás siendo intensa',
    duration: 'pausa',
    type: 'pausa',
    kicker: 'Cita interna',
    fromCuaderno: { slug: 'hipervigilancia', title: 'Hipervigilancia' },
    pageIndex: 6,
    icon: '"',
    color: 'coral',
  },

  // ─── EJERCICIOS DEL CURSO IEPP (Psicología Positiva 2.0) ───────────────
  // Apuntan a "Tu mejor yo" hasta que se publiquen sus cuadernos propios.
  // Mientras tanto, el slug 'tu-mejor-yo' es nuestro cuaderno de cabecera de
  // psicología positiva (B1M05 + B2M04 + B1M07 mezclados).
  {
    id: 'visualizacion-mejor-yo',
    title: 'Visualización · Tu mejor yo',
    duration: '~15 min',
    type: 'ejercicio',
    kicker: 'Seligman · clásico',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 4,
    icon: '★',
    color: 'mostaza',
  },
  {
    id: 'visita-gratitud',
    title: 'Visita de gratitud',
    duration: '~30 min',
    type: 'ejercicio',
    kicker: 'Gratitud · IEPP B2M04',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 6,
    icon: '✉',
    color: 'coral',
  },
  {
    id: 'diario-gratitud-5min',
    title: 'Diario de gratitud · 5 min',
    duration: '21 días',
    type: 'ejercicio',
    kicker: 'Gratitud diaria',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 7,
    icon: '∽',
    color: 'mostaza',
  },
  {
    id: 'body-scan-compasivo',
    title: 'Body scan compasivo',
    duration: '12 min',
    type: 'ejercicio',
    kicker: 'Autoconocimiento',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 8,
    icon: '◌',
    color: 'cobalto',
  },
  {
    id: 'flow-identifica',
    title: 'Identifica un momento de Flow',
    duration: '15 min',
    type: 'ejercicio',
    kicker: 'Csikszentmihalyi',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 9,
    icon: '∿',
    color: 'mostaza',
  },
  {
    id: 'jarron-roto',
    title: 'El jarrón roto',
    duration: '10 min',
    type: 'ejercicio',
    kicker: 'Aceptación · Kintsugi',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 10,
    icon: '⊘',
    color: 'coral',
  },
  {
    id: 'doble-vision',
    title: 'La doble visión',
    duration: '~20 min',
    type: 'ejercicio',
    kicker: 'PsiPos existencial',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 11,
    icon: '◎',
    color: 'cobalto',
  },
  {
    id: 'huevos-zanahorias-cafe',
    title: 'Huevos, zanahorias o café',
    duration: '10 min',
    type: 'ejercicio',
    kicker: 'Metáfora resiliencia',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 12,
    icon: '☕',
    color: 'coral',
  },
  {
    id: 'plan-presiliencia',
    title: 'Plan de presiliencia',
    duration: '~30 min',
    type: 'ejercicio',
    kicker: 'Anticipar dificultad',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 13,
    icon: '⛨',
    color: 'cobalto',
  },
  {
    id: 'tigre-hambriento',
    title: 'El tigre hambriento',
    duration: '~10 min',
    type: 'pausa',
    kicker: 'Cuento Cherokee',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 14,
    icon: '"',
    color: 'mostaza',
  },
  {
    id: 'sherlock-interior',
    title: 'Sherlock Holmes interior',
    duration: '~15 min',
    type: 'ejercicio',
    kicker: 'Curiosidad',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 15,
    icon: '?',
    color: 'mostaza',
  },
  {
    id: 'woop',
    title: 'WOOP · deseo + plan',
    duration: '~20 min',
    type: 'ejercicio',
    kicker: 'Planificación',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 16,
    icon: '☉',
    color: 'cobalto',
  },
  {
    id: 'comunicacion-no-violenta',
    title: 'Comunicación no violenta',
    duration: '~25 min',
    type: 'ejercicio',
    kicker: 'Rosenberg · CNV',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 17,
    icon: '◇',
    color: 'coral',
  },
  {
    id: 'rincon-belleza',
    title: 'El rincón de la belleza',
    duration: 'continuo',
    type: 'pausa',
    kicker: 'Apreciación · diaria',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 18,
    icon: '✿',
    color: 'mostaza',
  },
  {
    id: 'oasis-desierto',
    title: 'Oasis en el desierto',
    duration: '~15 min',
    type: 'ejercicio',
    kicker: 'PsiPos existencial',
    fromCuaderno: { slug: 'tu-mejor-yo', title: 'Tu mejor yo' },
    pageIndex: 19,
    icon: '◯',
    color: 'mostaza',
  },
];
